version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  game-listing-app:
    image: game-listing-app
    restart: always
    ports:
      - 5000:80
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      "ListingDatabaseSettings:ConnectionString": mongodb://root:example@mongo:27017/